CC = gcc
CFLAGS = -Wall

SERVER_SOURCES = serveur.c
CLIENT_SOURCES = client.c
HEADERS = serv_cli_fifo.h Handlers_serv.h Handlers_cli.h

SERVER_EXECUTABLE = serveur
CLIENT_EXECUTABLE = client

all:	$(SERVER_EXECUTABLE) $(CLIENT_EXECUTABLE)

$(SERVER_EXECUTABLE):	$(SERVER_SOURCES) $(HEADERS)
	$(CC) $(CFLAGS) -o $(SERVER_EXECUTABLE) $(SERVER_SOURCES)

$(CLIENT_EXECUTABLE):$(CLIENT_SOURCES) $(HEADERS)
	$(CC) $(CFLAGS) -o $(CLIENT_EXECUTABLE) $(CLIENT_SOURCES)

run_server: $(SERVER_EXECUTABLE)
	./$(SERVER_EXECUTABLE)

run_client: $(CLIENT_EXECUTABLE)
	./$(CLIENT_EXECUTABLE)

clean:
	rm -f $(SERVER_EXECUTABLE) $(CLIENT_EXECUTABLE)

.PHONY:all clean run_server run_client
